ALTER TABLE transaction
ALTER COLUMN status TYPE VARCHAR(30)
    USING status::VARCHAR(30),
    ADD CONSTRAINT check_status CHECK (status IN ('AVAILABLE', 'IN_EXCHANGE', 'COMPLETED', 'CANCELED', 'INACTIVE'));
